### ISSUE TITLE
Watch out for extraneous spaces that decrease readability

### ISSUE THREAD

**Issue by karl-project-review** [SlinkyLincy/intro-data-capstone-biodiversity#2]
https://github.com/SlinkyLincy/intro-data-capstone-biodiversity/blob/8666b27f6069db09ced697dee3c533bfbb10dcc7/Petra%20submission/biodiversity.py#L190
The extra spaces between the if and else statements could make this line difficult to read, as we have to scroll far to the left to read the else statement, and if someone were glancing through the code quickly, they might miss the else statement entirely. Try to remove extra spaces like this.

**Comment by SlinkyLincy** [comment]
Addressed in commit 3b15cb7
