### ISSUE TITLE
Remember inplace parameter when using .rename()

### ISSUE THREAD

**Issue by karl-project-review** [SlinkyLincy/intro-data-capstone-biodiversity#3]
https://github.com/SlinkyLincy/intro-data-capstone-biodiversity/blob/8666b27f6069db09ced697dee3c533bfbb10dcc7/Petra%20submission/biodiversity.py#L240
In order for the results of the .rename() method to be stored, we either need to assign the results of the statement to a variable or else use the inplace parameter, like so:
```python
category_pivot.rename(columns = {'False' : 'not_protected', 'True' : 'protected'}, inplace=True)
```

**Comment by SlinkyLincy** [comment]
Addressed in commit 3b15cb7
