### ISSUE TITLE
The baseline conversion rate is the prevalence in the control group, ie Bryce

### ISSUE THREAD

**Issue by karl-project-review** [SlinkyLincy/intro-data-capstone-biodiversity#4]
https://github.com/SlinkyLincy/intro-data-capstone-biodiversity/blob/8666b27f6069db09ced697dee3c533bfbb10dcc7/Petra%20submission/biodiversity.py#L440
This ties in to the issue in your readme file. The sample size is the same for both Bryce and Yellowstone, and it is calculated by using the known prevalence rate of foot and mouth disease in our control population, which is Bryce (where no new efforts to control the disease are being made). The 10% number is not the baseline rate in Yellowstone. It was just an example to show the 5% means a change from the 15% baseline to 10% or lower as opposed a change of 5% of that 15% (ie it is saying 5% change does not mean a change of 5% of 15% = 0.75%, or from 15% to 14.25% or lower). So, we don't know what the new prevalence rate is in Yellowstone, but we are comparing it against the 15% starting rate in Bryce which we are assuming is a standard prevalence rate in the parks (whether that is a valid assumption to make is another question). So, the sample size should be 510 for both. Sorry if the wording in the question wasn't clear on this.

**Comment by SlinkyLincy** [comment]
Addressed in commit 3b15cb7

It might be worth re-wording the question.
