### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by karl-project-review** [SlinkyLincy/intro-data-capstone-biodiversity#5]
Good job with this overall! Most of your code does as it should, and the majority of your calculations are correct. However, as explained in Issue #1, we need to account for duplicate species by using nunique(), and the p-values in your project are off because this was not done. Also, as explained in Issue #4, the baseline conversion rate refers to the control group's expected conversion rate (ie the 15% in Bryce national park), and this rate is used in the sample size calculations for both parks. We don't have an initial estimate for what the new rate is in Yellowstone, and that 10% number was only being used as an example of the minimum amount of change that we would consider significant. I would recommend you go back through and fix these errors to make sure you have these concepts internalized, as while they are small fixes, they are important and affect the results of the study.

Your report walks us through the study well, using visual aids effectively to aid our understanding. Making the bar charts green to match the color theme was a particularly nice touch, and it was good to include the p-values of the experiments and provide interpretations of them. However, I would encourage you to also include the significance thresholds for the tests, to clarify what level of evidence we were looking for. Also, good work including reasonable conclusions based on the tests performed.

Again, I would encourage you to go back and fix up the issues with the duplicates and the sample size, as with a few small fixes, this project will be in great shape. Well done!

(Approaches Expectations)

**Comment by SlinkyLincy** [comment]
All issues are addressed in commit 3b15cb7

Thanks for you feedback.
